export enum ChannelType {
  AMAZON = 'Amazon',
  WALMART = 'Walmart',
  EBAY = 'eBay',
  SEARS = 'Sears',
  SHOPIFY = 'Shopify'
};

export enum StoreType {
  HAB = 'Hat and Beyond',
  MA = 'Ma Croix',
};

export enum AmazonSPFeedTypes {
  JSON_LISTINGS_FEED = 'JSON_LISTINGS_FEED',
  POST_PRODUCT_DATA = 'POST_PRODUCT_DATA',
  POST_INVENTORY_AVAILABILITY_DATA = 'POST_INVENTORY_AVAILABILITY_DATA',
  POST_PRODUCT_OVERRIDES_DATA = 'POST_PRODUCT_OVERRIDES_DATA',
  POST_PRODUCT_PRICING_DATA = 'POST_PRODUCT_PRICING_DATA',
  POST_PRODUCT_IMAGE_DATA = 'POST_PRODUCT_IMAGE_DATA',
  POST_PRODUCT_RELATIONSHIP_DATA = 'POST_PRODUCT_RELATIONSHIP_DATA',
  POST_FLAT_FILE_INVLOADER_DATA = 'POST_FLAT_FILE_INVLOADER_DATA',
  POST_FLAT_FILE_LISTINGS_DATA = 'POST_FLAT_FILE_LISTINGS_DATA',
  POST_FLAT_FILE_BOOKLOADER_DATA_ = 'POST_FLAT_FILE_BOOKLOADER_DATA_',
  POST_FLAT_FILE_CONVERGENCE_LISTINGS_DATA = 'POST_FLAT_FILE_CONVERGENCE_LISTINGS_DATA',
  POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA = 'POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA',
  POST_UIEE_BOOKLOADER_DATA = 'POST_UIEE_BOOKLOADER_DATA',
  POST_STD_ACES_DATA = 'POST_STD_ACES_DATA',
  POST_ORDER_ACKNOWLEDGEMENT_DATA = 'POST_ORDER_ACKNOWLEDGEMENT_DATA',
  POST_PAYMENT_ADJUSTMENT_DATA = 'POST_PAYMENT_ADJUSTMENT_DATA',
  POST_ORDER_FULFILLMENT_DATA = 'POST_ORDER_FULFILLMENT_DATA',
  POST_INVOICE_CONFIRMATION_DATA = 'POST_INVOICE_CONFIRMATION_DATA',
  POST_EXPECTED_SHIP_DATE_SOD = 'POST_EXPECTED_SHIP_DATE_SOD',
  POST_FLAT_FILE_ORDER_ACKNOWLEDGEMENT_DATA = 'POST_FLAT_FILE_ORDER_ACKNOWLEDGEMENT_DATA',
  POST_FLAT_FILE_PAYMENT_ADJUSTMENT_DATA = 'POST_FLAT_FILE_PAYMENT_ADJUSTMENT_DATA',
  POST_FLAT_FILE_FULFILLMENT_DATA = 'POST_FLAT_FILE_FULFILLMENT_DATA',
  POST_EXPECTED_SHIP_DATE_SOD_FLAT_FILE = 'POST_EXPECTED_SHIP_DATE_SOD_FLAT_FILE',
}

export enum AmazonSPFeedProcessingStatuses {
  CANCELLED = 'CANCELLED',
  DONE = 'DONE',
  FATAL = 'FATAL',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_QUEUE = 'IN_QUEUE',
}

export enum AmazonSPFeedDocumentContentTypes {
  TSV = 'TSV',
  XML = 'XML',
  JSON = 'JSON',
}

export enum AmazonSPFeedDocumentStandardEncryptionTypes {
  AES = 'AES'
}

export enum AmazonSPFeedDocumentCompressionAlgorithm {
  GZIP = 'GZIP'
}

export enum AmazonSPFeedProcessingStatusTypes {
  CANCELLED = 'CANCELLED',
  DONE = 'DONE',
  FATAL = 'FATAL',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_QUEUE = 'IN_QUEUE',
}

export enum AmazonSPPatchOperations {
  ADD = 'add',
  REPLACE = 'replace',
  DELETE = 'delete',
}

export enum AmazonSPListingsFeedOperationTypes {
  UPDATE = 'UPDATE',
  PARTIAL_UPDATE = 'PARTIAL_UPDATE',
  PATCH = 'PATCH',
  DELETE = 'DELETE',
}

export enum AmazonSPListingsFeedRequirements {
  LISTING = 'LISTING',
  LISTING_PRODUCT_ONLY = 'LISTING_PRODUCT_ONLY',
  LISTING_OFFER_ONLY = 'LISTING_OFFER_ONLY',
}